from typing import List, Tuple

movie_db: List[Tuple[str, str, int, List[str], str]] = [
    (
        "amarcord",
        "federico fellini",
        1974,
        [
            "magali noel",
            "bruno zanin",
            "pupella maggio",
            "armando drancia",
        ],
        "Drama",
    ),
    (
        "the big easy",
        "jim mcbride",
        1987,
        [
            "dennis quaid",
            "ellen barkin",
            "ned beatty",
            "lisa jane persky",
            "john goodman",
            "charles ludlam",
        ],
        "Crime",
    ),
    (
        "boyz n the hood",
        "john singleton",
        1991,
        [
            "cuba gooding jr.",
            "ice cube",
            "larry fishburne",
            "tyra ferrell",
            "morris chestnut",
        ],
        "Drama",
    ),
    (
        "dead again",
        "kenneth branagh",
        1991,
        [
            "kenneth branagh",
            "emma thompson",
            "andy garcia",
            "derek jacobi",
            "hanna schygulla",
        ],
        "Mystery",
    ),
    (
        "the godfather",
        "francis ford coppola",
        1972,
        ["marlon brando", "al pacino", "james caan", "robert duvall", "diane keaton"],
        "Crime",
    ),
    (
        "an american in paris",
        "vincente minnelli",
        1952,
        ["gene kelley", "leslie caron", "oscar levant", "nina foch", "george guetary"],
        "Musical",
    ),
    (
        "casablanca",
        "michael curtiz",
        1942,
        [
            "humphrey bogart",
            "ingrid bergman",
            "paul henreid",
            "claude rains",
            "sydney greenstreet",
            "peter lorre",
            "s z sakall",
            "conrad veidt",
            "dooley wilson",
        ],
        "Drama",
    ),
    (
        "citizen kane",
        "orson welles",
        1941,
        [
            "orson welles",
            "joseph cotten",
            "dorothy comingore",
            "ray collins",
            "george coulouris",
            "agnes moorehead",
            "ruth warrick",
        ],
        "Drama",
    ),
    (
        "gone with the wind",
        "victor fleming",
        1939,
        [
            "clark gable",
            "vivien leigh",
            "leslie howard",
            "olivia de havilland",
            "hattie mcdaniel",
            "butterfly mcqueen",
        ],
        "Drama",
    ),
    (
        "lawrence of arabia",
        "david lean",
        1962,
        [
            "peter otoole",
            "alec guinness",
            "anthony quinn",
            "jack hawkins",
            "jose ferrer",
            "omar sharif",
            "anthony quayle",
            "claude rains",
            "arthur kennedy",
            "donald wolfit",
        ],
        "Adventure",
    ),
    (
        "the manchurian candidate",
        "john frankenheimer",
        1962,
        [
            "frank sinatra",
            "laurence harvey",
            "janet leigh",
            "angela lansbury",
            "henry silva",
            "james gregory",
            "leslie parrish",
            "john mcgiver",
            "khigh dhiegh",
            "james edwards",
        ],
        "Thriller",
    ),
    (
        "metropolis",
        "fritz lang",
        1926,
        [
            "alfred abel",
            "gustay frohlich",
            "brigitte helm",
            "rudolf kleinrogge",
            "heinrich george",
        ],
        "Science Fiction",
    ),
    (
        "othello",
        "orson welles",
        1952,
        [
            "orson welles",
            "michael mac liammoir",
            "robert coote",
            "suzanne cloutier",
            "faye compton",
            "doris dowling",
            "michael laurence",
        ],
        "Drama",
    ),
    (
        "spartacus",
        "stanley kubrick",
        1960,
        [
            "kirk douglas",
            "laurence olivier",
            "jean simmons",
            "charles laughton",
            "peter ustinov",
            "john gavin",
            "tony curtis",
            "woody strode",
        ],
        "Historical",
    ),
    (
        "a star is born",
        "george cuckor",
        1954,
        [
            "judy garland",
            "james mason",
            "jack carson",
            "tommy noonan",
            "charles bickford",
        ],
        "Musical",
    ),
    (
        "after the rehearsal",
        "ingmar bergman",
        1984,
        ["erland josephson", "ingrid thulin", "lena olin", "nadja palmstjerna-weiss"],
        "Drama",
    ),
    (
        "amadeus",
        "milos forman",
        1984,
        [
            "f murray abraham",
            "tom hulce",
            "elizabeth berridge",
            "simon callow",
            "roy dotrice",
            "christine ebersole",
            "jeffrey jones",
        ],
        "Drama",
    ),
    (
        "blood simple",
        "joel coen",
        1985,
        [
            "john getz",
            "frances mcdormand",
            "dan hedaya",
            "m emmet walsh",
            "samm-art williams",
        ],
        "Crime",
    ),
    (
        "chinatown",
        "roman polanski",
        1974,
        [
            "jack nicholson",
            "faye dunaway",
            "john huston",
            "perry lopez",
            "john hillerman",
            "darrell zwerling",
            "diane ladd",
            "roman polanski",
        ],
        "Mystery",
    ),
    (
        "the cotton club",
        "francis ford coppola",
        1984,
        [
            "richard gere",
            "gregory hines",
            "diane lane",
            "lonette mckee",
            "bob hoskins",
            "james remar",
            "fred gwynne",
        ],
        "Crime",
    ),
    (
        "the crying game",
        "neil jordan",
        1992,
        [
            "stephen rea",
            "jaye davidson",
            "forest whitaker",
            "miranda richardson",
            "adrian dunbar",
            "breffini mckenna",
            "joe savino",
        ],
        "Drama",
    ),
    (
        "the day of the jackal",
        "fred zinnemann",
        1973,
        [
            "edward fox",
            "terence alexander",
            "michel auclair",
            "alan badel",
            "tony britton",
            "denis carey",
            "olga georges-picot",
            "cyril cusack",
        ],
        "Thriller",
    ),
    (
        "diva",
        "jean-jacques beineix",
        1981,
        [
            "wilhelmenia wiggins fernandez",
            "frederic andrei",
            "richard bohringer",
            "thay an luu",
            "jacques fabbri",
            "chantal deruaz",
        ],
        "Crime",
    ),
    (
        "the dresser",
        "peter yates",
        1984,
        ["albert finney", "tom courtenay", "edward fox", "zena walker"],
        "Drama",
    ),
    (
        "el norte",
        "gregory nava",
        1983,
        [
            "zaide silvia gutierrez",
            "david villalpando",
            "ernesto gomez cruz",
            "alicia del lago",
            "trinidad silva",
        ],
        "Drama",
    ),
    (
        "the exorcist",
        "william friedkin",
        1973,
        [
            "ellen burstyn",
            "linda blair",
            "jason miller",
            "max von sydow",
            "kitty winn",
            "lee j cobb",
        ],
        "Horror",
    ),
    (
        "a fish called wanda",
        "michael chrichton",
        1988,
        [
            "john cleese",
            "jamie lee curtis",
            "kevin kline",
            "michael palin",
            "maria aitken",
            "tom georgeson",
            "patricia hayes",
        ],
        "Comedy",
    ),
    (
        "flirting",
        "john duigan",
        1992,
        [
            "noah taylor",
            "thandie newton",
            "nicole kidman",
            "bartholomew rose",
            "felix nobis",
            "josh picker",
            "kiri paramore",
        ],
        "Drama",
    ),
    ("gates of heaven", "errol morris", 1978, [], "Documentary"),
    (
        "house of games",
        "david mamet",
        1987,
        [
            "lindsay crouse",
            "joe mantegna",
            "mike nussman",
            "lilia skala",
            "j t walsh",
            "jack wallace",
        ],
        "Crime",
    ),
    (
        "iceman",
        "fred schepisi",
        1984,
        ["timothy hutton", "john lone", "lindsay crouse"],
        "Drama",
    ),
    (
        "jaws",
        "steven spielberg",
        1975,
        [
            "roy scheider",
            "robert shaw",
            "richard dreyfuss",
            "lorraine gary",
            "murray hamilton",
        ],
        "Thriller",
    ),
    (
        "johnny got his gun",
        "dalton trumbo",
        1971,
        [
            "timothy bottoms",
            "kathy fields",
            "jason robards",
            "diane varsi",
            "donald sutherland",
            "eduard franz",
        ],
        "Drama",
    ),
    (
        "local hero",
        "bill forsyth",
        1983,
        [
            "burt lancaster",
            "peter reigert",
            "peter capaldi",
            "fulton mckay",
            "denis lawson",
        ],
        "Comedy",
    ),
    (
        "malcolm x",
        "spike lee",
        1992,
        [
            "denzel washington",
            "angela basset",
            "albert hall",
            "al freeman jr",
            "delroy lindo",
            "spike lee",
        ],
        "Biography",
    ),
    (
        "a clockwork orange",
        "stanley kubrick",
        1971,
        [
            "malcolm mcdowell",
            "patrick magee",
            "adrienne corri",
            "warren clarke",
            "michael bates",
        ],
        "Crime",
    ),
    (
        "the deer hunter",
        "michael cimino",
        1978,
        [
            "robert de niro",
            "christopher walken",
            "meryl streep",
            "john cazale",
            "john savage",
        ],
        "Drama",
    ),
    (
        "dial m for murder",
        "alfred hitchcock",
        1954,
        [
            "ray milland",
            "grace kelly",
            "robert cummings",
            "john williams",
            "anthony dawson",
        ],
        "Mystery",
    ),
    (
        "do the right thing",
        "spike lee",
        1989,
        [
            "danny aiello",
            "ossie davis",
            "ruby dee",
            "spike lee",
            "bill nunn",
        ],
        "Drama",
    ),
    (
        "eternal sunshine of the spotless mind",
        "michel gondry",
        2004,
        [
            "jim carrey",
            "kate winslet",
            "tom wilkinson",
            "kirsten dunst",
            "mark ruffalo",
        ],
        "Romance",
    ),
    (
        "the french connection",
        "william friedkin",
        1971,
        [
            "gene hackman",
            "roy scheider",
            "fernando rey",
            "tony lo bianco",
            "marcel bozzuffi",
        ],
        "Action",
    ),
    (
        "heat",
        "michael mann",
        1995,
        [
            "al pacino",
            "robert de niro",
            "val kilmer",
            "jon voight",
            "tom sizemore",
        ],
        "Crime",
    ),
    (
        "jaws",
        "steven spielberg",
        1975,
        [
            "roy scheider",
            "robert shaw",
            "richard dreyfuss",
            "lorraine gary",
            "murray hamilton",
        ],
        "Thriller",
    ),
    (
        "jurassic park",
        "steven spielberg",
        1993,
        [
            "sam neill",
            "laura dern",
            "jeff goldblum",
            "richard attenborough",
            "martin ferrero",
        ],
        "Adventure",
    ),
    (
        "kill bill: vol. 1",
        "quentin tarantino",
        2003,
        [
            "uma thurman",
            "david carradine",
            "daryl hannah",
            "michael madsen",
            "lucy liu",
        ],
        "Action",
    ),
    (
        "the last emperor",
        "bernardo bertolucci",
        1987,
        [
            "john lone",
            "joan chen",
            "peter o'toole",
            "ruocheng ying",
            "victor wong",
        ],
        "Biography",
    ),
    (
        "the maltese falcon",
        "john huston",
        1941,
        [
            "humphrey bogart",
            "mary astor",
            "gladys george",
            "peter lorre",
            "barton maclane",
        ],
        "Film-Noir",
    ),
    (
        "a nightmare on elm street",
        "wes craven",
        1984,
        [
            "heather langenkamp",
            "johnny depp",
            "robert englund",
            "ronee blakley",
            "amanda wyss",
        ],
        "Horror",
    ),
    (
        "no country for old men",
        "joel coen, ethan coen",
        2007,
        [
            "tommy lee jones",
            "javier bardem",
            "josh brolin",
            "woody harrelson",
            "kelly macdonald",
        ],
        "Crime",
    ),
    (
        "pulp fiction",
        "quentin tarantino",
        1994,
        [
            "john travolta",
            "uma thurman",
            "samuel l. jackson",
            "bruce willis",
            "tim roth",
        ],
        "Crime",
    ),
    (
        "the shawshank redemption",
        "frank darabont",
        1994,
        [
            "tim robbins",
            "morgan freeman",
            "bob gunton",
            "william sadler",
            "clancy brown",
        ],
        "Drama",
    ),
    (
        "the shining",
        "stanley kubrick",
        1980,
        [
            "jack nicholson",
            "shelley duvall",
            "danny lloyd",
            "scatman crothers",
            "barry nelson",
        ],
        "Horror",
    ),
    (
        "star wars: episode iv - a new hope",
        "george lucas",
        1977,
        [
            "mark hamill",
            "harrison ford",
            "carrie fisher",
            "alec guinness",
            "peter cushing",
        ],
        "Sci-Fi",
    ),
    (
        "taxi driver",
        "martin scorsese",
        1976,
        [
            "robert de niro",
            "jodie foster",
            "cybill shepherd",
            "harvey keitel",
            "albert brooks",
        ],
        "Crime",
    ),
    (
        "the wizard of oz",
        "victor fleming",
        1939,
        [
            "judy garland",
            "frank morgan",
            "ray bolger",
            "bert lahr",
            "jack haley",
        ],
        "Adventure",
    ),
    (
        "the silence of the lambs",
        "jonathan demme",
        1991,
        [
            "jodie foster",
            "anthony hopkins",
            "lawrence a. bonney",
            "scott glenn",
            "anthony heald",
        ],
        "Crime",
    ),
]